"""Input definitions and UI metadata. Units are explicit; pressures are absolute bar."""
from pydantic import BaseModel, Field, ConfigDict

def parameter(default, title, unit, group, low, high, description, step=1):
    return Field(default, title=title, ge=low, le=high, description=description,
                 json_schema_extra={"unit": unit, "group": group, "step": step})

class EngineConfig(BaseModel):
    model_config = ConfigDict(extra="forbid", allow_inf_nan=False)
    chamber_pressure_bar: float = parameter(100,"Chamber pressure","bar","Design point",20,250,"Full-throttle chamber-pressure setpoint.")
    target_thrust_kn: float = parameter(100,"Target vacuum thrust","kN","Design point",20,250,"Full-throttle sizing target; nozzle area is resized after edits.")
    throttle: float = parameter(1,"Throttle","fraction","Design point",0.05,1.2,"Illustrative operating range 0.60–1.00.",0.01)
    mixture_ratio: float = parameter(3.4,"O/F mixture ratio","kg/kg","Design point",1,8,"Total tank-fed oxygen / methane mass flow.",0.1)
    expansion_ratio: float = parameter(45,"Nozzle expansion ratio","Ae/At","Design point",5,120,"Vacuum nozzle exit area / throat area.")
    lox_tank_pressure_bar: float = parameter(4,"LOX tank pressure","bar","Tanks & lines",1,15,"Absolute tank pressure.",0.1)
    fuel_tank_pressure_bar: float = parameter(4,"Methane tank pressure","bar","Tanks & lines",1,15,"Absolute tank pressure.",0.1)
    lox_density: float = parameter(1140,"LOX density","kg/m³","Tanks & lines",800,1300,"Constant illustrative liquid density.")
    fuel_density: float = parameter(422,"Methane density","kg/m³","Tanks & lines",250,550,"Constant illustrative liquid density.")
    lox_pipe_diameter_mm: float = parameter(75,"LOX line diameter","mm","Tanks & lines",15,150,"Equivalent feed-line internal diameter.")
    fuel_pipe_diameter_mm: float = parameter(65,"Fuel line diameter","mm","Tanks & lines",15,150,"Equivalent feed-line internal diameter.")
    lox_pipe_length_m: float = parameter(2,"LOX line length","m","Tanks & lines",0.1,20,"Equivalent length, half upstream and half downstream of pump.",0.1)
    fuel_pipe_length_m: float = parameter(2.5,"Fuel line length","m","Tanks & lines",0.1,20,"Equivalent length, half upstream and half downstream of pump.",0.1)
    filter_loss_bar: float = parameter(0.12,"Filter pressure loss","bar","Tanks & lines",0,5,"Each filter loss at its full-design flow; scales with flow squared.",0.01)
    lox_pump_outlet_bar: float = parameter(145,"LOX pump outlet target","bar","Pumps & turbine",30,400,"Full-speed pressure rise is fixed relative to nominal suction; restrictions lower delivered outlet.")
    fuel_pump_outlet_bar: float = parameter(150,"Fuel pump outlet target","bar","Pumps & turbine",30,400,"Full-speed pressure-rise target including cooling allowance.")
    booster_rise_bar: float = parameter(3,"Booster pressure rise","bar","Pumps & turbine",0,15,"Illustrative low-pressure booster rise.",0.1)
    lox_pump_efficiency: float = parameter(0.75,"LOX pump efficiency","fraction","Pumps & turbine",0.3,0.95,"Hydraulic power / shaft power.",0.01)
    fuel_pump_efficiency: float = parameter(0.72,"Fuel pump efficiency","fraction","Pumps & turbine",0.3,0.95,"Hydraulic power / shaft power.",0.01)
    turbine_efficiency: float = parameter(0.78,"Turbine efficiency","fraction","Pumps & turbine",0.2,0.95,"Isentropic expansion efficiency; shaft efficiency fixed at 0.97.",0.01)
    preburner_boost_bar: float = parameter(370,"Preburner boost outlet","bar","Pumps & turbine",80,600,"Separate common-shaft branch boosters supply only preburner flows. Included in power demand.")
    lox_valve_kv: float = parameter(180,"Main LOX valve Kv","m³/h","Valves",1,400,"Water-based metric Kv at 1 bar drop; effective Kv = Kv × opening.")
    fuel_valve_kv: float = parameter(150,"Main fuel valve Kv","m³/h","Valves",1,400,"Linear opening approximation, not a real valve characteristic.")
    preburner_valve_kv: float = parameter(8,"Preburner fuel valve Kv","m³/h","Valves",0.1,50,"Kv for the small methane branch control valve.",0.1)
    preburner_lox_valve_kv: float = parameter(20,"Preburner LOX valve Kv","m³/h","Valves",0.5,100,"Kv for the oxygen branch control valve.",0.5)
    lox_valve_opening: float = parameter(100,"Main LOX valve opening","%","Valves",0,100,"Requested opening, in addition to timeline gate.")
    fuel_valve_opening: float = parameter(100,"Main fuel valve opening","%","Valves",0,100,"Requested opening, in addition to timeline gate.")
    preburner_valve_opening: float = parameter(100,"Preburner fuel opening","%","Valves",0,100,"Requested preburner fuel-valve opening.")
    preburner_lox_valve_opening: float = parameter(100,"Preburner LOX opening","%","Valves",0,100,"Requested preburner oxygen-valve opening.")
    cooling_pressure_drop_bar: float = parameter(12,"Cooling pressure drop","bar","Cooling & injection",0,70,"At full-design main fuel flow; scales with flow squared.")
    injector_pressure_drop_bar: float = parameter(20,"Required injector drop","bar","Cooling & injection",5,60,"Full-design injector requirement; scales with flow squared.")
    preburner_lox_fraction: float = parameter(0.25,"LOX to preburner","fraction","Preburner split",0.01,0.95,"Fraction of total LOX routed to the boosted preburner branch.",0.01)
    preburner_fuel_fraction: float = parameter(0.025,"Fuel to preburner","fraction","Preburner split",0.001,0.3,"Small methane fraction; remaining methane cools the main chamber.",0.001)
    idle_duration: float = parameter(1,"Safe / idle duration","s","Timeline",0.5,10,"Educational time, not a firing procedure.",0.5)
    purge_duration: float = parameter(3,"Purge duration","s","Timeline",0.5,20,"Line and chamber conditioning illustration.",0.5)
    spinup_duration: float = parameter(3,"Pump spin-up duration","s","Timeline",0.5,20,"An external starter is assumed.",0.5)
    preburner_duration: float = parameter(2,"Preburner ignition duration","s","Timeline",0.5,20,"Schematic transition to turbine drive.",0.5)
    ignition_duration: float = parameter(2,"Main ignition duration","s","Timeline",0.5,20,"Brief main-chamber ignition illustration.",0.5)
    ramp_duration: float = parameter(5,"Ramp duration","s","Timeline",0.5,30,"Interpolation to the requested design state.",0.5)
    steady_duration: float = parameter(12,"Steady-state duration","s","Timeline",1,120,"Dwell before the demonstration shuts down.")
    shutdown_duration: float = parameter(4,"Shutdown duration","s","Timeline",1,30,"Controlled decay followed by a short purge.",0.5)

